config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :exercises
  resources :contacts
  get '/about' => 'pages#about'
  get '/privacy' => 'pages#privacy'
  root 'pages#home'
  
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
     
    validates :date, presence: true
    validates :weight, presence: true
    validates :reps, presence: true 
    belongs_to :user
    
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :exercises
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
    
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
      
            ContactMailer.contact_email(name, email, body).deliver
      
            flash[:success] = "Message sent."
            redirect_to new_contact_path 
        else
            flash[:danger] = "Error occured, message has not been sent."
            redirect_to new_contact_path 
        end
    end
    
    private
        def contact_params
            params.require(:contact).permit(:name, :email, :comments)
        end
    
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
   before_filter :authenticate_user!
  
  # GET /exercises
  def index
  end

  # GET /exercises/1
  def show
    @exercises = current_user.exercises.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end
  

  # GET /exercises/new
  def new
    @exercise = current_user.exercises.build
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  def create
    @exercise = current_user.exercises.build(exercise_params)

      if @exercise.save
         flash[:success] = "Workout Created!"
         redirect_to exercise_path(current_user) 
      else
         flash[:danger] = "You must enter weight and reps!"
        render action: 'new' 
      end
      
  end

  # PATCH/PUT /exercises/1
  def update
     
      if @exercise.update(exercise_params)
         redirect_to @exercise, notice: 'Exercise was successfully updated.'
      else
         render action: 'edit' 
      end
  end

  # DELETE /exercises/1
  def destroy
     @exercise = Exercise.find(params[:id])
     @exercise.destroy 
     redirect_to exercise_url 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:date, :exercise, :weight, :reps, :max, :bulk, :tone, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
    end
    
    def about
    end
    
    def privacy
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    </br>
    <h2 class="text-center">Contact Us</h2>
    <p class="text-center">Reach out if you have any questions or comments.</p>
    </br>  
  		
    <div class="well">
      <%= form_for @contact do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :comments %>
          <%= f.text_area :comments, class: 'form-control' %>
        </div>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <% end %>
    </div>
    
  </div>
</div>
 

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
   
  
  <div class="well bye"> 
    <div class="form-group">
      <%= f.label :date %><br>
      <%= f.date_select :date, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :exercise %><br>
      <%= f.text_field :exercise, class:'form-control', placeholder: 'Enter Exercise' %>
    </div>
    <div class="form-group">
      <%= f.label :weight %><br>
      <%= f.number_field :weight, class:'form-control', id:"weight", placeholder: 'Enter Weight' %>
    </div>
    <div class="form-group">
      <%= f.label :reps %><br>
    <%= f.number_field :reps, in: 1.0..10.0, class:'form-control', id:"reps", placeholder: 'Enter Reps 1 to 10' %>
     </div>

     
     <div class="actions" id="submit">
      <%= f.submit value:'Calculate', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
  
	
	
	 
	<div class="well space"> 				
    <div class="form-group has-success">
      <%= f.label "Your One Rep Max" %><br>
      <%= f.number_field :max, class:'form-control', id:"onerepmax" %>
    </div>
    <div class="field">
      <%= f.label "Your work out weight for bulking up" %><br>
      <%= f.number_field :bulk, class:'form-control', id:"bwow" %> 
    </div>
    <div class="field">
      <%= f.label "Your work out weight for toning up" %><br>
      <%= f.number_field :tone, class:'form-control', id:"wow" %>  
    </div>
    
   
     <div class="actions">
      <%= f.submit value:'Save', class: 'btn btn-primary btn-block submit'%>
    </div>
  </div>
  
<% end %>
</br>
</br>

  

app/views/exercises/create.js.erb
$

app/views/exercises/edit.html.erb
<h1>Editing Exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1"> 
 
<p id="notice"><%= notice %></p>

<h1 class="text-center">Exercise History</h1>
</br>
 <%= will_paginate %>
 </br>
 
<% @exercises.each do |exercise| %>
<ul class="list-group">
  <li class="list-group-item list-group-item-info"><%= exercise.date.strftime("%b %d %Y")%></li>
  <li class="list-group-item">Exercise Performed: <%= exercise.exercise %></li>
  <li class="list-group-item">Weight Used: <%= exercise.weight %> lbs.</li>
  <li class="list-group-item">Number of Reps Performed: <%= exercise.reps %> reps</li>
  <li class="list-group-item list-group-item-success">Your One Rep Max: <%= exercise.max %> lbs.</li>
  <li class="list-group-item">Workout Body Building Weight: <%= exercise.bulk %> lbs.</li>
  <li class="list-group-item">Workout Body Toning Weight: <%= exercise.tone %> lbs.</li>
  <li class="list-group-item">Delete Workout: <%= link_to 'Delete', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></li>
</ul>
</br>
</br>
<%end%> 
 
<br>
 <%= will_paginate %>
<%= link_to 'New Exercise', new_exercise_path %>

<!--Google adwords-->
  <div class="row" id="ads">
				<div class="col-xs-12 col-md-6 col-md-offset-3">
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">
					</script>
					<!-- OneRepMax -->
					<ins class="adsbygoogle"
						 style="display:block"
						 data-ad-client="ca-pub-0579466747730468"
						 data-ad-slot="5801665806"
						 data-ad-format="auto"></ins>
					<script>
						(adsbygoogle = window.adsbygoogle || []).push({});
					</script>
				</div>
	</div>
	
	
	
 
 

</div>
</div>

app/views/exercises/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
  	</br>
		<h2 class="text-center">New Workout</h2>
	</br>
	    <%= render 'form' %>
 </div>
</div>
 

app/views/exercises/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1"> 
    </br>
    </br>
    <h2 class="text-center">Exercise History</h2>
     
     <%= will_paginate %>
    </br>
     
         <% @exercises.each do |exercise| %>
          
        <ul class="list-group">
          <li class="list-group-item list-group-item-info"><%= exercise.date.strftime("%b %d %Y")%></li>
          <li class="list-group-item">Exercise Performed: <%= exercise.exercise %></li>
          <li class="list-group-item">Weight Used: <%= exercise.weight %> lbs.</li>
          <li class="list-group-item">Number of Reps Performed: <%= exercise.reps %> reps</li>
          <li class="list-group-item list-group-item-success">Your One Rep Max: <%= exercise.max %> lbs.</li>
          <li class="list-group-item">Workout Body Building Weight: <%= exercise.bulk %> lbs.</li>
          <li class="list-group-item">Workout Body Toning Weight: <%= exercise.tone %> lbs.</li>
          <li class="list-group-item">Delete Workout: <%= link_to 'Delete', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
        </br>
        <% end %>
        <%= link_to 'New Workout', new_exercise_path %>
         
        <br>
        <%= will_paginate %>
     

        <!--Google adwords-->
          <div class="row" id="ads">
        	<div class="col-xs-12 col-md-6 col-md-offset-3">
        		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">
        		</script>
        		<!-- OneRepMax -->
        		<ins class="adsbygoogle"
        			 style="display:block"
        			 data-ad-client="ca-pub-0579466747730468"
        			 data-ad-slot="5801665806"
        			 data-ad-format="auto"></ins>
        		<script>
        			(adsbygoogle = window.adsbygoogle || []).push({});
        		</script>
        	</div>
          </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!--start of Footer section-->
      <footer class="text-center" id="footer">
        <div class="row">
          <div class="col-xs-12 col-md-12">
        <li><%= link_to "Privacy Policy", privacy_path %></li>
        <h4>&copy; GetMyOneRepMax.com</h4>
        
        
        <!--google analytics div-->
      
      <section id="google_analytics">
      <script>
			  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
			
			  ga('create', 'UA-65100343-2', 'auto');
			  ga('send', 'pageview');
			
			</script>
	    </section><!--end of google analytics-->
     
          </div><!--end of row-->
        </div>
      </footer> 
      
      
       

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>One Rep Max Calculator</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
   <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
      <i class="fa fa-users"></i>
      One Rep Max Calculator
      <% end %>
    </div>
    
    <div class="collapse navbar-collapse" id="main-nav-collapse">
         <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", new_contact_path %></li>
         
          <% if user_signed_in? %>
            <li><%= link_to "New Workout", new_exercise_path %></li>
            <li><%= link_to "History", exercise_path(current_user) %></li>
            <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %></li>
          <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= button_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %></li>
          <% end %>
         </ul>
    </div><!-- /.navbar-collapse -->
    
  </div>
</nav>

    <div class="container-fluid">
      
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
    
      <%= yield %> 
    
      <%= render 'layouts/footer' %>
    </div>
 	  
</body>
</html>

app/views/pages/about.html.erb
<div class="row">
    <div class="col-md-7 col-md-offset-3">
           </br>
           </br>
           </br>
           <h2>About</h2>
           
           </br>
           <p>My name is <b>Jevon</b>. I am an aspiring <b>Ruby on Rails Full Stack Web Developer</b> and I enjoy staying in shape. I began to lift weights because unlike most people, I was extremely underweight. That lead me to take a weight training class in college, to try to see if I could find a way to gain weight. I have been skinny all of my life. Standing at 6'2 I was very skinny to be honest.</p></br>
           <p>Well anyways while in the class I learned about the <em>Brzycki formula</em>. Around that same time I was taking advanced visual basic and I had to come up with an application for my final exam. Over the semester I had begun to put on weight due to eating right and lifting heavy. So I had the thought of placing the Brzycki formula into an app for my final exam.</p></br>
           <p>I did that and got a good grade on the final. So then I thought I should make a website to help others who need to learn how much they should be lifting and to also help people safely determine their one rep max. With that desire <b>GetMyOneRepMax.com</b> was born. I hope this website will help you reach what ever your health goals are. Please share with a friend, good luck and God bless.</p></br>
   </div><!--end of 1st col-->
</div>

app/views/pages/home.html.erb
<!--Main section for home page-->
 
<div class="row" id="top-main">
  <div class="col-md-6 col-xs-12">
      <h1 class="text-center">ONE REP MAX</h1>
      <h2 class="text-center" id="title-subtext">Calculator</h2>
      <%= image_tag("home1.png", :alt => "main picture", class:"img-responsive center-block") %>
  </div>
  
	  <!--Home page form-->
  <div class="col-md-4 col-md-offset-1 col-xs-12">
      <form  id="FormID" class="well">
		  <div class="form-group">
			<label for="weight">Weight Used:</label>
			<input type="text" class="form-control"  id="weight" name="weight" placeholder="Weight">
		  </div>
		  
		  <div class="form-group">
			<label for="Reps Performed"># of Reps Performed up to 10:</label>
			<input type="text" class="form-control"   id="reps" name="reps" placeholder="Reps">
		  </div>
		  
		  <div id="box1" class="form-group">
		   <h4 class="text-center lead">Your one rep max is:</h4>
			 <h3 id="repmax" name="repmax" class="text-center lead">0</h3>
		  </div>
						  
		  <button type="text" class="btn btn-default btn-block btn-primary" id="submit">One Rep Max</button>
	  </form>
  </div>
</div> <!--End of Class Row-->  
 


<!--Bottom Section for Home Page-->
 
	<div class="row"> 
    	<div class="col-md-6 col-xs-12 lead">
    		<p class="instructions lead"><span><b>Instructions:</b></span> This formula works by choosing a weight you <em>do not</em> think you can lift 10 times.</p>
    		<p class="lead">After your set enter the weight lifted and reps performed. The result will be your estimated one rep max.<p>
    	 
    	
    	<div class="well cta">
            <p class="lead text-center">Sign up for free and keep track of your workouts.</p>
            <br/>
            <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-primary btn-lg btn-block' %>
        </div>
       </div>
	
      <div class="col-md-6 col-xs-12">
       <h3 class="text-center">Brzycki Formula</h3>
        <table class="table table-bordered text-center">
          <tr>
             <th scope="col" class="text-center"># of Reps Performed</th>
             <th scope="col" class="text-center">Multilication coefficient</th>
          </tr>
          <tr>
             <td>1</td>
             <td>1.000</td>
          </tr>
          <tr>
             <td>2</td>
             <td>1.029</td>
          </tr>
          <tr>
             <td>3</td>
             <td>1.059</td>
          </tr>
          <tr>
             <td>4</td>
             <td>1.091</td>
          </tr>
          <tr>
             <td>5</td>
             <td>1.125</td>
          </tr>
          <tr>
             <td>6</td>
             <td>1.161</td>
          </tr>
          <tr>
             <td>7</td>
             <td>1.200</td>
          </tr>
          <tr>
             <td>8</td>
             <td>1.242</td>
          </tr>
          <tr>
             <td>9</td>
             <td>1.286</td>
          </tr>
          <tr>
             <td>10</td>
             <td>1.330</td>
         </tr>
        </table>
      </div>
   </div><!--End of row-->
  
 
 

app/views/pages/privacy.html.erb
 
		 
       <div class="row">
         <div class="col-xs-12 col-md-8 col-md-offset-2">
           <h2>Privacy Policy</h2>
           <strong>What information do we collect?</strong> 
     <br/>
     <br/><span>We collect information from you when you register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.  </span>
     <br/>
     <br/><span>When ordering or registering on our site, as appropriate, you may be asked to enter your: name or e-mail address. You may, however, visit our site anonymously.</span>
     <br/>
     <br/><span>Google, as a third party vendor, uses cookies to serve ads on your site.
Google&#8217;s use of the DART cookie enables it to serve ads to your users based on their visit to your sites and other sites on the Internet.
Users may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy..</span>
     <br/>
     <br/><strong>What do we use your information for?</strong> 
     <br/>
     <br/><span>Any of the information we collect from you may be used in one of the following ways: </span>
     <br/>
     <br/><span>; To personalize your experience</span>
     <br/><span>(your information helps us to better respond to your individual needs)</span>
     <br/>
     <br/><span>; To improve our website</span>
     <br/><span>(we continually strive to improve our website offerings based on the information and feedback we receive from you)</span>
     <br/>
     <br/><span>; To improve customer service</span>
     <br/><span>(your information helps us to more effectively respond to your customer service requests and support needs)</span>
     <br/>
     <br/><span>; To process transactions</span>
     <br/>
     <blockquote>Your information, whether public or private, will not be sold, exchanged, transferred, or given to any other company for any reason whatsoever, without your consent, other than for the express purpose of delivering the purchased product or service requested.</blockquote>
     <br/><span>; To administer a contest, promotion, survey or other site feature</span>
     <br/>
     <br/>
     <br/><span>; To send periodic emails</span>
     <br/>
     <blockquote>The email address you provide for order processing, may be used to send you information and updates pertaining to your order, in addition to receiving occasional company news, updates, related product or service information, etc.</blockquote>
     <br/>
     <br/><strong>How do we protect your information?</strong> 
     <br/>
     <br/><span>We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. </span>
     <br/>
     <br/><span>We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to?keep the information confidential.</span>
     <br/>
     <br/><span>After a transaction, your private information (credit cards, social security numbers, financials, etc.) will not be kept on file for more than 60 days.</span>
     <br/>
     <br/><strong>Do we use cookies?</strong> 
     <br/>
     <br/><span>Yes (Cookies are small files that a site or its service provider transfers to your computers hard drive through your Web browser (if you allow) that enables the sites or service providers systems to recognize your browser and capture and remember certain information</span>
     <br/>
     <br/><span> We use cookies to help us remember and process the items in your shopping cart, understand and save your preferences for future visits, keep track of advertisements and compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.</span>
     <br/>
     <br/><strong>Do we disclose any information to outside parties?</strong> 
     <br/>
     <br/><span>We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.</span>
     <br/>
     <br/><strong>Third party links</strong> 
     <br/>
     <br/><span> Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.</span>
     <br/>
     <br/><strong>California Online Privacy Protection Act Compliance</strong>
     <br/>
     <br/><span>Because we value your privacy we have taken the necessary precautions to be in compliance with the California Online Privacy Protection Act. We therefore will not distribute your personal information to outside parties without your consent.</span>
     <br/>
     <br/><strong>Childrens Online Privacy Protection Act Compliance</strong> 
     <br/>
     <br/><span>We are in compliance with the requirements of COPPA (Childrens Online Privacy Protection Act), we do not collect any information from anyone under 13 years of age. Our website, products and services are all directed to people who are at least 13 years old or older.</span>
     <br/>
     <br/><strong>Online Privacy Policy Only</strong> 
     <br/>
     <br/><span>This online privacy policy applies only to information collected through our website and not to information collected offline.</span>
     <br/>
     <br/><strong>Your Consent</strong> 
     <br/>
     <br/><span>By using our site, you consent to our </span><a style="text-decoration:none; color:#3C3C3C;" href="http://www.freeprivacypolicy.com/" target="_blank">privacy policy</a><span>.</span>
     <br/>
     <br/><strong>Changes to our Privacy Policy</strong> 
     <br/>
     <br/><span>If we decide to change our privacy policy, we will post those changes on this page. </span>
     <br/>
     <br/><span>jevonhayter@gmail.com</span>
     <br/>
           </div><!--end of 1st col-->
       </div>